import Head from 'next/head';
import Image from 'next/image';
import { Banner } from '../components/banner/banner';
import styles from '../styles/Home.module.css';
import { Pagination } from 'react-bootstrap';
import { useEffect, useState } from 'react';

export default function Home() {
    const [currentPage, setCurrentPage] = useState(7);
    const [pageNumberLimit, setPageNumberLimit] = useState(7);
    const [maxPageNumberLimit, setMaxPageNumberLimit] = useState(7);
    const [minPageNumberLimit, setMinPageNumberLimit] = useState(0);
    let totalNumber = 100;

    const handleOnBannerClick = () => {
        console.log('hi banner button');
    };
    const items = [];
    for (let number = 1; number <= totalNumber; number++) {
        items.push(number);
    }

    

    const handleNext = () => {
        setCurrentPage(currentPage + 1);
        if (currentPage + 1 > maxPageNumberLimit) {
            setMaxPageNumberLimit(maxPageNumberLimit + pageNumberLimit);
            setMinPageNumberLimit(minPageNumberLimit + pageNumberLimit);
        }
    };

    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta
                        name='description'
                        content='Generated by create next app'
                    />
                    <link rel='icon' href='/favicon.ico' />
                </Head>
                <main className={styles.main}>
                    <Banner
                        buttonText='View stores nearby'
                        handleOnClick={handleOnBannerClick}
                    />
                </main>
            </div>

            <ul className='d-inline-block'>
                {items.map((number) => {
                    if (
                        number < maxPageNumberLimit + 1 &&
                        number > minPageNumberLimit
                    ) {
                        return (
                            <li
                                key={number}
                                id={number}
                                className={
                                    currentPage == number ? 'active' : null
                                }
                            >
                                {number}
                            </li>
                        );
                    }
                })}

                <li>
                    <button onClick={handleNext}>next</button>
                </li>
            </ul>

            <button
                onClick={() => {
                    setCurrentPage(24);
                }}
            >
                set
            </button>
        </>
    );
}

export const getStaticProps = async (context) => {
    console.log(context);
    return {
        props: {},
    };
};
